theme: jekyll-theme-cayman
title: Ellis QPhML 2020 Virtual Meeting
description: Ellis Fellows QPhML

logo: /assets/images/ellis-logo-transparent-1.png

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
